Repository swing-park/sidedish, pull requests merged in 2021-04, with the labels that each got.

#10 Feat: 스프링 데이터 jdbc으로 셋팅하라
  backend/sidedish/build.gradle
  backend/sidedish/src/main/resources/application.properties
  backend/sidedish/src/main/resources/schema.sql
Labels: BE

#11 Feat: domain을 생성해라
  backend/sidedish/src/main/java/codsquad/team17/sidedish/domain/BestCategory.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/domain/DishCategory.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/domain/Image.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/domain/Item.java
Labels: BE, Pair programming

#12 Feat: repository를 생성해라
  backend/sidedish/src/main/java/codsquad/team17/sidedish/repository/BestCategoryRepository.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/repository/DishCategoryRepository.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/repository/ImageRepository.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/repository/ItemRepository.java
Labels: BE, Pair programming

#17 Fix : DB 스키마 변경하라
  backend/sidedish/src/main/java/codsquad/team17/sidedish/domain/Image.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/domain/Item.java
  backend/sidedish/src/main/resources/data.sql
  backend/sidedish/src/main/resources/schema.sql
Labels: BE, Pair programming

#18 Feat: controller를 만들어라
  backend/sidedish/src/main/java/codsquad/team17/sidedish/controller/BestCategoryController.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/BestCategoryDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/ItemDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/repository/ItemRepository.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/service/BestCategoryService.java
  backend/sidedish/src/main/resources/data.sql
Labels: BE, Pair programming

#21 Feature create get method
  backend/sidedish/src/main/java/codsquad/team17/sidedish/controller/BestCategoryController.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/domain/BestCategory.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/domain/DishCategory.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/domain/Image.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/domain/Item.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/BestCategoryDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/ItemDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/repository/ImageRepository.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/repository/ItemRepository.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/service/BestCategoryService.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/service/ImageService.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/service/ItemService.java
  backend/sidedish/src/main/resources/data.sql
Labels: BE, Pair programming

#22 style : ItemDto item 변수명을 변경하라.
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/ItemDto.java
Labels: BE, Pair programming

#24 Feat: DishCategory 조회 기능을 구현해라
  backend/sidedish/src/main/java/codsquad/team17/sidedish/controller/DishCategoryController.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/domain/BestCategory.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/BestCategoryDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/DishCategoryDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/ItemDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/repository/ItemRepository.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/service/BestCategoryService.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/service/DishCategoryService.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/service/ItemService.java
Labels: BE, Pair programming

#29 Feature create detail
  backend/sidedish/src/main/java/codsquad/team17/sidedish/controller/BestCategoryController.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/controller/DishCategoryController.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/controller/ItemDetailController.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/domain/Item.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/BestCategoryDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/DishCategoryDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/ItemDetailDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/ItemDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/RecommandedItemDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/repository/ImageRepository.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/repository/ItemRepository.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/service/BestCategoryService.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/service/DishCategoryService.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/service/ImageService.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/service/ItemDetailService.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/service/ItemService.java
  backend/sidedish/src/main/resources/data.sql
  backend/sidedish/src/main/resources/schema.sql
Labels: BE, Pair programming

#36 refactor : API관련 내용을 수정하라.
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/ItemDetailDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/ItemDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/RecommandedItemDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/repository/ItemRepository.java
  backend/sidedish/src/main/resources/data.sql
Labels: BE, Pair programming

#37 feat : CORS 기능을 구현하라.
  backend/sidedish/src/main/java/codsquad/team17/sidedish/config/WebConfig.java
Labels: BE, Pair programming

#39 style : URL 추가 / 제거
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/ItemDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/RecommandedItemDto.java
Labels: BE, Pair programming

#43 style : 중복된 URL을 제거하라.
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/ItemDetailDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/ItemDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/RecommendedItemDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/service/ItemDetailService.java
Labels: BE, Pair programming

#45 Fix: dish url
  backend/sidedish/src/main/resources/data.sql
Labels: BE, Pair programming

#50 [BE] feature order
  backend/sidedish/src/main/java/codsquad/team17/sidedish/controller/OrderController.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/domain/Item.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/OrderDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/service/OrderService.java
Labels: BE, Pair programming

#55 refactor : RequestBody 형태로 데이터를 전달받아라.
  backend/sidedish/src/main/java/codsquad/team17/sidedish/controller/OrderController.java
Labels: BE, Pair programming

#56 [BE] 주문하기 기능 완료.
  backend/sidedish/.gitignore
  backend/sidedish/build.gradle
  backend/sidedish/gradle/wrapper/gradle-wrapper.jar
  backend/sidedish/gradle/wrapper/gradle-wrapper.properties
  backend/sidedish/gradlew
  backend/sidedish/gradlew.bat
  backend/sidedish/settings.gradle
  backend/sidedish/src/main/java/codsquad/team17/sidedish/SidedishApplication.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/config/WebConfig.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/controller/BestCategoryController.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/controller/DishCategoryController.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/controller/ItemDetailController.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/controller/OrderController.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/domain/BestCategory.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/domain/DishCategory.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/domain/Image.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/domain/Item.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/BestCategoryDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/DishCategoryDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/ItemDetailDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/ItemDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/OrderDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/RecommendedItemDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/repository/BestCategoryRepository.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/repository/DishCategoryRepository.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/repository/ImageRepository.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/repository/ItemRepository.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/service/BestCategoryService.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/service/DishCategoryService.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/service/ItemDetailService.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/service/ItemService.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/service/OrderService.java
  backend/sidedish/src/main/resources/application.properties
  backend/sidedish/src/main/resources/data.sql
  backend/sidedish/src/main/resources/schema.sql
  backend/sidedish/src/test/java/codsquad/team17/sidedish/SidedishApplicationTests.java
Labels: BE, Pair programming

#61 Feat: 커스텀 이셉션 핸들러를 이용하여 예외를 처리
  backend/sidedish/src/main/java/codsquad/team17/sidedish/controller/BestCategoryController.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/controller/DishCategoryController.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/controller/ItemDetailController.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/controller/OrderController.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/ExceptionResponseDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/OrderDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/exception/BestCategoryNotFoundException.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/exception/DishCategoryNotFoundException.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/exception/GlobalExceptionHandler.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/exception/ImageNotFoundException.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/exception/ItemNotFoundException.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/exception/ItemStockEmptyException.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/service/BestCategoryService.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/service/DishCategoryService.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/service/ItemDetailService.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/service/ItemService.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/service/OrderService.java
Labels: BE, Pair programming

#62 feat : CORS 설정에 PUT METHOD를 추가하라.
  backend/sidedish/src/main/java/codsquad/team17/sidedish/config/WebConfig.java
Labels: BE, Pair programming

#63 [FE] slider 컴포넌트 완성
  FE/banchan-project/src/BestItems/BestItems.jsx
  FE/banchan-project/src/BestItems/BestItemsUI/BestItemsTab/BestItemsTab.jsx
  FE/banchan-project/src/BestItems/BestItemsUI/BestItemsTab/BestItemsTabTitle.jsx
  FE/banchan-project/src/MainItems/MainItemsStyles.jsx
  FE/banchan-project/src/Slider/Slider.jsx
  FE/banchan-project/src/Slider/SliderButtons/SliderButtons.jsx
  FE/banchan-project/src/Slider/SliderButtons/SliderLeftButton.jsx
  FE/banchan-project/src/Slider/SliderButtons/SliderRightButton.jsx
  FE/banchan-project/src/Slider/SliderCard/SliderCard.jsx
  FE/banchan-project/src/Slider/SliderCard/SliderCardList.jsx
  FE/banchan-project/src/Slider/SliderCard/SliderCardWrapper.jsx
  FE/banchan-project/src/Slider/SliderStyles.jsx
Labels: FE

#64 [BE] exception handler 및 CORS put 요청에 대한 PR 보냅니다
  backend/sidedish/src/main/java/codsquad/team17/sidedish/config/WebConfig.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/controller/BestCategoryController.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/controller/DishCategoryController.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/controller/ItemDetailController.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/controller/OrderController.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/ExceptionResponseDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/OrderDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/exception/BestCategoryNotFoundException.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/exception/DishCategoryNotFoundException.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/exception/GlobalExceptionHandler.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/exception/ImageNotFoundException.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/exception/ItemNotFoundException.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/exception/ItemStockEmptyException.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/service/BestCategoryService.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/service/DishCategoryService.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/service/ItemDetailService.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/service/ItemService.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/service/OrderService.java
Labels: BE, Pair programming

#66 chore : jackson databind dependency를 추가하라.
  backend/sidedish/build.gradle
Labels: BE, Pair programming

#67 [BE] jackson-databind dependency 추가하라.
  backend/sidedish/build.gradle
Labels: BE, Pair programming

#73 style : 코드에 개행과 정렬을 맞춰라.
  backend/sidedish/src/main/java/codsquad/team17/sidedish/controller/BestCategoryController.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/controller/DishCategoryController.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/controller/ItemDetailController.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/controller/OrderController.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/domain/BestCategory.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/domain/DishCategory.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/domain/Image.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/domain/Item.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/BestCategoryDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/DishCategoryDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/ItemDetailDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/ItemDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/OrderDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/RecommendedItemDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/exception/BestCategoryNotFoundException.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/exception/DishCategoryNotFoundException.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/exception/GlobalExceptionHandler.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/exception/ImageNotFoundException.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/exception/ItemNotFoundException.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/exception/ItemStockEmptyException.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/repository/ImageRepository.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/repository/ItemRepository.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/service/BestCategoryService.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/service/DishCategoryService.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/service/ItemDetailService.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/service/ItemService.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/service/OrderService.java
Labels: BE, Pair programming

#75 [BE]style : 전체 코드의 개행과 정렬을 맞춰라.
  backend/sidedish/src/main/java/codsquad/team17/sidedish/controller/BestCategoryController.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/controller/DishCategoryController.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/controller/ItemDetailController.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/controller/OrderController.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/domain/BestCategory.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/domain/DishCategory.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/domain/Image.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/domain/Item.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/BestCategoryDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/DishCategoryDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/ItemDetailDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/ItemDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/OrderDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/RecommendedItemDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/exception/BestCategoryNotFoundException.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/exception/DishCategoryNotFoundException.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/exception/GlobalExceptionHandler.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/exception/ImageNotFoundException.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/exception/ItemNotFoundException.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/exception/ItemStockEmptyException.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/repository/ImageRepository.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/repository/ItemRepository.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/service/BestCategoryService.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/service/DishCategoryService.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/service/ItemDetailService.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/service/ItemService.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/service/OrderService.java
Labels: BE, Pair programming
